type NotificationTopic {
  id: ID!
  name: String!
  deleteable: Boolean!
  createdAt: DateTime!
}

type NotificationTopicQueryResult {
  topics: [NotificationTopic!]!
  total: Int!
}

type Query {
  listTopics(name: String): NotificationTopicQueryResult!
  getTopic(id: ID!): NotificationTopic
}

type Mutation {
  createTopic(name: String!): NotificationTopic!  @isAuthenticated @hasRole(roles: [admin])
  deleteTopic(id: ID!): Boolean!  @isAuthenticated @hasRole(roles: [admin])
}
